# First, we define a sample config.yaml content and a parser in Python

import yaml
from pathlib import Path

# Define sample configuration dictionary
sample_config = {
    'simulation': {
        'map_size': [8, 8],
        'num_drones': 4,
        'max_turns': 100,
        'communication_mode': 'colocation_broadcast',
        'allow_strategy_change': True,
        'strategy_change_only_on_king_tile': True,
        'seed': 42
    },
    'logging': {
        'log_level': 'INFO',
        'log_file': 'simulation.log'
    }
}

# Save this configuration as a YAML file
config_path = Path('config.yaml')
with config_path.open('w') as f:
    yaml.dump(sample_config, f)

# Function to read config
def load_config(config_file='config.yaml'):
    with open(config_file, 'r') as f:
        return yaml.safe_load(f)

# Load config to test
config = load_config()
config
